export const SP500_CONSTITUENTS: { symbol: string; name: string; sector: string; roe: number | null }[] = [
  { symbol: "MMM", name: "3M", sector: "Industrial Conglomerates", roe: 75.5 },
  { symbol: "AOS", name: "A. O. Smith", sector: "Building Products", roe: 29.2 },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Health Care Equipment", roe: 13 },
  { symbol: "ABBV", name: "AbbVie", sector: "Biotechnology", roe: 6225 },
  { symbol: "ACN", name: "Accenture", sector: "IT Consulting & Other Services", roe: 25 },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Application Software", roe: 55.4 },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Semiconductors", roe: 7.1 },
  { symbol: "AES", name: "AES Corporation", sector: "Independent Power Producers & Energy Traders", roe: 5.1 },
  { symbol: "AFL", name: "Aflac", sector: "Life & Health Insurance", roe: 13.1 },
  { symbol: "A", name: "Agilent Technologies", sector: "Life Sciences Tools & Services", roe: 20.6 },
  { symbol: "APD", name: "Air Products", sector: "Industrial Gases", roe: -1.7 },
  { symbol: "ABNB", name: "Airbnb", sector: "Hotels, Resorts & Cruise Lines", roe: 30.2 },
  { symbol: "AKAM", name: "Akamai Technologies", sector: "Internet Services & Infrastructure", roe: 9.2 },
  { symbol: "ALB", name: "Albemarle Corporation", sector: "Specialty Chemicals", roe: -4.7 },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", sector: "Office REITs", roe: -5.9 },
  { symbol: "ALGN", name: "Align Technology", sector: "Health Care Supplies", roe: 10.4 },
  { symbol: "ALLE", name: "Allegion", sector: "Building Products", roe: 36.1 },
  { symbol: "LNT", name: "Alliant Energy", sector: "Electric Utilities", roe: 11.3 },
  { symbol: "ALL", name: "Allstate", sector: "Property & Casualty Insurance", roe: 39.5 },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", sector: "Interactive Media & Services", roe: 35.7 },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", sector: "Interactive Media & Services", roe: 35.7 },
  { symbol: "MO", name: "Altria", sector: "Tobacco", roe: NaN },
  { symbol: "AMZN", name: "Amazon", sector: "Broadline Retail", roe: 22.3 },
  { symbol: "AMCR", name: "Amcor", sector: "Paper & Plastic Packaging Products & Materials", roe: 7.7 },
  { symbol: "AEE", name: "Ameren", sector: "Multi-Utilities", roe: 11.3 },
  { symbol: "AEP", name: "American Electric Power", sector: "Electric Utilities", roe: 12.5 },
  { symbol: "AXP", name: "American Express", sector: "Consumer Finance", roe: 34 },
  { symbol: "AIG", name: "American International Group", sector: "Multi-line Insurance", roe: 7.4 },
  { symbol: "AMT", name: "American Tower", sector: "Telecom Tower REITs", roe: 28.8 },
  { symbol: "AWK", name: "American Water Works", sector: "Water Utilities", roe: 10.5 },
  { symbol: "AMP", name: "Ameriprise Financial", sector: "Asset Management & Custody Banks", roe: 60.5 },
  { symbol: "AME", name: "Ametek", sector: "Electrical Components & Equipment", roe: 14.6 },
  { symbol: "AMGN", name: "Amgen", sector: "Biotechnology", roe: 106.1 },
  { symbol: "APH", name: "Amphenol", sector: "Electronic Components", roe: 36.9 },
  { symbol: "ADI", name: "Analog Devices", sector: "Semiconductors", roe: 7.9 },
  { symbol: "AON", name: "Aon plc", sector: "Insurance Brokers", roe: 46.9 },
  { symbol: "APA", name: "APA Corporation", sector: "Oil & Gas Exploration & Production", roe: 27.4 },
  { symbol: "APO", name: "Apollo Global Management", sector: "Asset Management & Custody Banks", roe: 14.7 },
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology Hardware, Storage & Peripherals", roe: 152 },
  { symbol: "AMAT", name: "Applied Materials", sector: "Semiconductor Materials & Equipment", roe: 38.9 },
  { symbol: "APP", name: "AppLovin", sector: "Application Software", roe: 212.9 },
  { symbol: "APTV", name: "Aptiv", sector: "Automotive Parts & Equipment", roe: 1.9 },
  { symbol: "ACGL", name: "Arch Capital Group", sector: "Property & Casualty Insurance", roe: 19.5 },
  { symbol: "ADM", name: "Archer Daniels Midland", sector: "Agricultural Products & Services", roe: 4.7 },
  { symbol: "ARES", name: "Ares Management", sector: "Asset Management & Custody Banks", roe: 13.6 },
  { symbol: "ANET", name: "Arista Networks", sector: "Communications Equipment", roe: 31.4 },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Insurance Brokers", roe: 6.9 },
  { symbol: "AIZ", name: "Assurant", sector: "Multi-line Insurance", roe: 15.9 },
  { symbol: "T", name: "AT&T", sector: "Integrated Telecommunication Services", roe: 18.8 },
  { symbol: "ATO", name: "Atmos Energy", sector: "Gas Utilities", roe: 9.2 },
  { symbol: "ADSK", name: "Autodesk", sector: "Application Software", roe: 40.3 },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Human Resource & Employment Services", roe: 73.8 },
  { symbol: "AZO", name: "AutoZone", sector: "Automotive Retail", roe: NaN },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "Multi-Family Residential REITs", roe: 8.9 },
  { symbol: "AVY", name: "Avery Dennison", sector: "Paper & Plastic Packaging Products & Materials", roe: 30.2 },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Aerospace & Defense", roe: 10 },
  { symbol: "BKR", name: "Baker Hughes", sector: "Oil & Gas Equipment & Services", roe: 14.6 },
  { symbol: "BALL", name: "Ball Corporation", sector: "Metal, Glass & Plastic Containers", roe: 16.1 },
  { symbol: "BAC", name: "Bank of America", sector: "Diversified Banks", roe: 10.2 },
  { symbol: "BAX", name: "Baxter International", sector: "Health Care Equipment", roe: -13.7 },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Health Care Equipment", roe: 7 },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Multi-Sector Holdings", roe: null },
  { symbol: "BBY", name: "Best Buy", sector: "Computer & Electronics Retail", roe: 22.5 },
  { symbol: "TECH", name: "Bio-Techne", sector: "Life Sciences Tools & Services", roe: 4 },
  { symbol: "BIIB", name: "Biogen", sector: "Biotechnology", roe: 7.4 },
  { symbol: "BLK", name: "BlackRock", sector: "Asset Management & Custody Banks", roe: 10.7 },
  { symbol: "BX", name: "Blackstone Inc.", sector: "Asset Management & Custody Banks", roe: 29.2 },
  { symbol: "XYZ", name: "Block, Inc.", sector: "Transaction & Payment Processing Services", roe: 14.7 },
  { symbol: "BK", name: "BNY Mellon", sector: "Asset Management & Custody Banks", roe: 12.9 },
  { symbol: "BA", name: "Boeing", sector: "Aerospace & Defense", roe: 290.1 },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Hotels, Resorts & Cruise Lines", roe: NaN },
  { symbol: "BSX", name: "Boston Scientific", sector: "Health Care Equipment", roe: 12.4 },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Pharmaceuticals", roe: 40.4 },
  { symbol: "AVGO", name: "Broadcom", sector: "Semiconductors", roe: 31 },
  { symbol: "BR", name: "Broadridge Financial Solutions", sector: "Data Processing & Outsourced Services", roe: 41.8 },
  { symbol: "BRO", name: "Brown & Brown", sector: "Insurance Brokers", roe: 11.2 },
  { symbol: "BF.B", name: "Brown–Forman", sector: "Distillers & Vintners", roe: null },
  { symbol: "BLDR", name: "Builders FirstSource", sector: "Building Products", roe: 10.1 },
  { symbol: "BG", name: "Bunge Global", sector: "Agricultural Products & Services", roe: 6 },
  { symbol: "BXP", name: "BXP, Inc.", sector: "Office REITs", roe: 4.9 },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Air Freight & Logistics", roe: 32.9 },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Application Software", roe: 21.9 },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Multi-Family Residential REITs", roe: 8.6 },
  { symbol: "CPB", name: "Campbell's Company (The)", sector: "Packaged Foods & Meats", roe: 14.8 },
  { symbol: "COF", name: "Capital One", sector: "Consumer Finance", roe: 2.4 },
  { symbol: "CAH", name: "Cardinal Health", sector: "Health Care Distributors", roe: NaN },
  { symbol: "CCL", name: "Carnival", sector: "Hotels, Resorts & Cruise Lines", roe: 25.6 },
  { symbol: "CARR", name: "Carrier Global", sector: "Building Products", roe: 10.9 },
  { symbol: "CVNA", name: "Carvana", sector: "Automotive Retail", roe: 67.9 },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Construction Machinery & Heavy Transportation Equipment", roe: 43.5 },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Financial Exchanges & Data", roe: 23.4 },
  { symbol: "CBRE", name: "CBRE Group", sector: "Real Estate Services", roe: 13.6 },
  { symbol: "CDW", name: "CDW Corporation", sector: "Technology Distributors", roe: 43 },
  { symbol: "COR", name: "Cencora", sector: "Health Care Distributors", roe: 133.5 },
  { symbol: "CNC", name: "Centene Corporation", sector: "Managed Health Care", roe: -28.7 },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Multi-Utilities", roe: 9.6 },
  { symbol: "CF", name: "CF Industries", sector: "Fertilizers & Agricultural Chemicals", roe: 23.4 },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Life Sciences Tools & Services", roe: -4.2 },
  { symbol: "SCHW", name: "Charles Schwab Corporation", sector: "Investment Banking & Brokerage", roe: 18.1 },
  { symbol: "CHTR", name: "Charter Communications", sector: "Cable & Satellite", roe: 28.7 },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Integrated Oil & Gas", roe: 7.2 },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Restaurants", roe: 47.4 },
  { symbol: "CB", name: "Chubb Limited", sector: "Property & Casualty Insurance", roe: 14.3 },
  { symbol: "CHD", name: "Church & Dwight", sector: "Household Products", roe: 17.6 },
  { symbol: "CIEN", name: "Ciena", sector: "Communications Equipment", roe: 4.4 },
  { symbol: "CI", name: "Cigna", sector: "Health Care Services", roe: 15.1 },
  { symbol: "CINF", name: "Cincinnati Financial", sector: "Property & Casualty Insurance", roe: 16 },
  { symbol: "CTAS", name: "Cintas", sector: "Diversified Support Services", roe: 43.4 },
  { symbol: "CSCO", name: "Cisco", sector: "Communications Equipment", roe: 23.8 },
  { symbol: "C", name: "Citigroup", sector: "Diversified Banks", roe: 6.8 },
  { symbol: "CFG", name: "Citizens Financial Group", sector: "Regional Banks", roe: 7.2 },
  { symbol: "CLX", name: "Clorox", sector: "Household Products", roe: 987.2 },
  { symbol: "CME", name: "CME Group", sector: "Financial Exchanges & Data", roe: 14.8 },
  { symbol: "CMS", name: "CMS Energy", sector: "Multi-Utilities", roe: 10.9 },
  { symbol: "KO", name: "Coca-Cola Company (The)", sector: "Soft Drinks & Non-alcoholic Beverages", roe: 43.3 },
  { symbol: "CTSH", name: "Cognizant", sector: "IT Consulting & Other Services", roe: 15.2 },
  { symbol: "COIN", name: "Coinbase", sector: "Financial Exchanges & Data", roe: 10.1 },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Household Products", roe: 497.5 },
  { symbol: "CMCSA", name: "Comcast", sector: "Cable & Satellite", roe: 21.4 },
  { symbol: "FIX", name: "Comfort Systems USA", sector: "Construction & Engineering", roe: 49.2 },
  { symbol: "CAG", name: "Conagra Brands", sector: "Packaged Foods & Meats", roe: -1.2 },
  { symbol: "COP", name: "ConocoPhillips", sector: "Oil & Gas Exploration & Production", roe: 12.4 },
  { symbol: "ED", name: "Consolidated Edison", sector: "Multi-Utilities", roe: 8.8 },
  { symbol: "STZ", name: "Constellation Brands", sector: "Distillers & Vintners", roe: 14.5 },
  { symbol: "CEG", name: "Constellation Energy", sector: "Electric Utilities", roe: 19.8 },
  { symbol: "COO", name: "Cooper Companies (The)", sector: "Health Care Supplies", roe: 4.6 },
  { symbol: "CPRT", name: "Copart", sector: "Diversified Support Services", roe: 17.1 },
  { symbol: "GLW", name: "Corning Inc.", sector: "Electronic Components", roe: 14.9 },
  { symbol: "CPAY", name: "Corpay", sector: "Transaction & Payment Processing Services", roe: 29.1 },
  { symbol: "CTVA", name: "Corteva", sector: "Fertilizers & Agricultural Chemicals", roe: 5 },
  { symbol: "CSGP", name: "CoStar Group", sector: "Real Estate Services", roe: 0.3 },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples Merchandise Retail", roe: 30.3 },
  { symbol: "CTRA", name: "Coterra", sector: "Oil & Gas Exploration & Production", roe: 11.9 },
  { symbol: "CRH", name: "CRH plc", sector: "Construction Materials", roe: 15.7 },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Systems Software", roe: -8.8 },
  { symbol: "CCI", name: "Crown Castle", sector: "Telecom Tower REITs", roe: NaN },
  { symbol: "CSX", name: "CSX Corporation", sector: "Rail Transportation", roe: 22.5 },
  { symbol: "CMI", name: "Cummins", sector: "Construction Machinery & Heavy Transportation Equipment", roe: 23.9 },
  { symbol: "CVS", name: "CVS Health", sector: "Health Care Services", roe: 2.3 },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Life Sciences Tools & Services", roe: 7.1 },
  { symbol: "DRI", name: "Darden Restaurants", sector: "Restaurants", roe: 54.1 },
  { symbol: "DDOG", name: "Datadog", sector: "Application Software", roe: 3.3 },
  { symbol: "DVA", name: "DaVita", sector: "Health Care Services", roe: 64.8 },
  { symbol: "DECK", name: "Deckers Brands", sector: "Footwear", roe: 39.7 },
  { symbol: "DE", name: "Deere & Company", sector: "Agricultural & Farm Machinery", roe: 19.6 },
  { symbol: "DELL", name: "Dell Technologies", sector: "Technology Hardware, Storage & Peripherals", roe: NaN },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Passenger Airlines", roe: 27.7 },
  { symbol: "DVN", name: "Devon Energy", sector: "Oil & Gas Exploration & Production", roe: 17.7 },
  { symbol: "DXCM", name: "Dexcom", sector: "Health Care Equipment", roe: 34.5 },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Oil & Gas Exploration & Production", roe: 10.9 },
  { symbol: "DLR", name: "Digital Realty", sector: "Data Center REITs", roe: 5.5 },
  { symbol: "DG", name: "Dollar General", sector: "Consumer Staples Merchandise Retail", roe: 16.5 },
  { symbol: "DLTR", name: "Dollar Tree", sector: "Consumer Staples Merchandise Retail", roe: 20.1 },
  { symbol: "D", name: "Dominion Energy", sector: "Multi-Utilities", roe: 9.2 },
  { symbol: "DPZ", name: "Domino's", sector: "Restaurants", roe: NaN },
  { symbol: "DASH", name: "DoorDash", sector: "Specialized Consumer Services", roe: 10.4 },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrial Machinery & Supplies & Components", roe: 15.3 },
  { symbol: "DOW", name: "Dow Inc.", sector: "Commodity Chemicals", roe: -13.8 },
  { symbol: "DHI", name: "D. R. Horton", sector: "Homebuilding", roe: 13.5 },
  { symbol: "DTE", name: "DTE Energy", sector: "Multi-Utilities", roe: 12.2 },
  { symbol: "DUK", name: "Duke Energy", sector: "Electric Utilities", roe: 9.7 },
  { symbol: "DD", name: "DuPont", sector: "Specialty Chemicals", roe: 0.5 },
  { symbol: "ETN", name: "Eaton Corporation", sector: "Electrical Components & Equipment", roe: 21.5 },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Broadline Retail", roe: 40.8 },
  { symbol: "ECL", name: "Ecolab", sector: "Specialty Chemicals", roe: 22.5 },
  { symbol: "EIX", name: "Edison International", sector: "Electric Utilities", roe: 24.1 },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Health Care Equipment", roe: 10.4 },
  { symbol: "EA", name: "Electronic Arts", sector: "Interactive Home Entertainment", roe: 10 },
  { symbol: "ELV", name: "Elevance Health", sector: "Managed Health Care", roe: 13.3 },
  { symbol: "EME", name: "Emcor", sector: "Construction & Engineering", roe: 37.1 },
  { symbol: "EMR", name: "Emerson Electric", sector: "Electrical Components & Equipment", roe: 9.6 },
  { symbol: "ETR", name: "Entergy", sector: "Electric Utilities", roe: 10.8 },
  { symbol: "EOG", name: "EOG Resources", sector: "Oil & Gas Exploration & Production", roe: 18.5 },
  { symbol: "EPAM", name: "EPAM Systems", sector: "IT Consulting & Other Services", roe: 10.3 },
  { symbol: "EQT", name: "EQT Corporation", sector: "Oil & Gas Exploration & Production", roe: 9 },
  { symbol: "EFX", name: "Equifax", sector: "Research & Consulting Services", roe: 13.8 },
  { symbol: "EQIX", name: "Equinix", sector: "Data Center REITs", roe: 9.7 },
  { symbol: "EQR", name: "Equity Residential", sector: "Multi-Family Residential REITs", roe: 10 },
  { symbol: "ERIE", name: "Erie Indemnity", sector: "Insurance Brokers", roe: 30.4 },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Multi-Family Residential REITs", roe: 12.2 },
  { symbol: "EL", name: "Estée Lauder Companies (The)", sector: "Personal Care Products", roe: -4.3 },
  { symbol: "EG", name: "Everest Group", sector: "Reinsurance", roe: 10.8 },
  { symbol: "EVRG", name: "Evergy", sector: "Electric Utilities", roe: 8.6 },
  { symbol: "ES", name: "Eversource Energy", sector: "Electric Utilities", roe: 10.8 },
  { symbol: "EXC", name: "Exelon", sector: "Electric Utilities", roe: 9.9 },
  { symbol: "EXE", name: "Expand Energy", sector: "Oil & Gas Exploration & Production", roe: 10.1 },
  { symbol: "EXPE", name: "Expedia Group", sector: "Hotels, Resorts & Cruise Lines", roe: 48.7 },
  { symbol: "EXPD", name: "Expeditors International", sector: "Air Freight & Logistics", roe: 36.5 },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Self-Storage REITs", roe: 7 },
  { symbol: "XOM", name: "ExxonMobil", sector: "Integrated Oil & Gas", roe: 11.1 },
  { symbol: "FFIV", name: "F5, Inc.", sector: "Communications Equipment", roe: 20.8 },
  { symbol: "FDS", name: "FactSet", sector: "Financial Exchanges & Data", roe: 28.8 },
  { symbol: "FICO", name: "Fair Isaac", sector: "Application Software", roe: NaN },
  { symbol: "FAST", name: "Fastenal", sector: "Trading Companies & Distributors", roe: 33.3 },
  { symbol: "FRT", name: "Federal Realty Investment Trust", sector: "Retail REITs", roe: 12.2 },
  { symbol: "FDX", name: "FedEx", sector: "Air Freight & Logistics", roe: 15.9 },
  { symbol: "FIS", name: "Fidelity National Information Services", sector: "Transaction & Payment Processing Services", roe: 1.2 },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Regional Banks", roe: 12.2 },
  { symbol: "FSLR", name: "First Solar", sector: "Semiconductors", roe: 16.9 },
  { symbol: "FE", name: "FirstEnergy", sector: "Electric Utilities", roe: 9.2 },
  { symbol: "FISV", name: "Fiserv", sector: "Transaction & Payment Processing Services", roe: NaN },
  { symbol: "F", name: "Ford Motor Company", sector: "Automobile Manufacturers", roe: -20.2 },
  { symbol: "FTNT", name: "Fortinet", sector: "Systems Software", roe: 135.7 },
  { symbol: "FTV", name: "Fortive", sector: "Industrial Machinery & Supplies & Components", roe: 6.4 },
  { symbol: "FOXA", name: "Fox Corporation (Class A)", sector: "Broadcasting", roe: 16.8 },
  { symbol: "FOX", name: "Fox Corporation (Class B)", sector: "Broadcasting", roe: 16.8 },
  { symbol: "BEN", name: "Franklin Resources", sector: "Asset Management & Custody Banks", roe: 4.5 },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Copper", roe: 13.9 },
  { symbol: "GRMN", name: "Garmin", sector: "Consumer Electronics", roe: 19.8 },
  { symbol: "IT", name: "Gartner", sector: "IT Consulting & Other Services", roe: 86.9 },
  { symbol: "GE", name: "GE Aerospace", sector: "Aerospace & Defense", roe: 44.7 },
  { symbol: "GEHC", name: "GE HealthCare", sector: "Health Care Equipment", roe: 22.4 },
  { symbol: "GEV", name: "GE Vernova", sector: "Heavy Electrical Equipment", roe: 42.6 },
  { symbol: "GEN", name: "Gen Digital", sector: "Systems Software", roe: 26.9 },
  { symbol: "GNRC", name: "Generac", sector: "Electrical Components & Equipment", roe: 6.3 },
  { symbol: "GD", name: "General Dynamics", sector: "Aerospace & Defense", roe: 17.7 },
  { symbol: "GIS", name: "General Mills", sector: "Packaged Foods & Meats", roe: 27.2 },
  { symbol: "GM", name: "General Motors", sector: "Automobile Manufacturers", roe: 4.3 },
  { symbol: "GPC", name: "Genuine Parts Company", sector: "Distributors", roe: 1.5 },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Biotechnology", roe: 40.7 },
  { symbol: "GPN", name: "Global Payments", sector: "Transaction & Payment Processing Services", roe: 4.8 },
  { symbol: "GL", name: "Globe Life", sector: "Life & Health Insurance", roe: 21.1 },
  { symbol: "GDDY", name: "GoDaddy", sector: "Internet Services & Infrastructure", roe: 369.5 },
  { symbol: "GS", name: "Goldman Sachs", sector: "Investment Banking & Brokerage", roe: 13.9 },
  { symbol: "HAL", name: "Halliburton", sector: "Oil & Gas Equipment & Services", roe: 12.3 },
  { symbol: "HIG", name: "Hartford (The)", sector: "Property & Casualty Insurance", roe: 21.7 },
  { symbol: "HAS", name: "Hasbro", sector: "Leisure Products", roe: -36.4 },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Health Care Facilities", roe: NaN },
  { symbol: "DOC", name: "Healthpeak Properties", sector: "Health Care REITs", roe: 1.2 },
  { symbol: "HSIC", name: "Henry Schein", sector: "Health Care Distributors", roe: 8.3 },
  { symbol: "HSY", name: "Hershey Company (The)", sector: "Packaged Foods & Meats", roe: 18.9 },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology Hardware, Storage & Peripherals", roe: 0.2 },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Hotels, Resorts & Cruise Lines", roe: NaN },
  { symbol: "HOLX", name: "Hologic", sector: "Health Care Equipment", roe: 10.9 },
  { symbol: "HD", name: "Home Depot (The)", sector: "Home Improvement Retail", roe: 162.9 },
  { symbol: "HON", name: "Honeywell", sector: "Industrial Conglomerates", roe: 26.1 },
  { symbol: "HRL", name: "Hormel Foods", sector: "Packaged Foods & Meats", roe: 6 },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Hotel & Resort REITs", roe: 11.5 },
  { symbol: "HWM", name: "Howmet Aerospace", sector: "Aerospace & Defense", roe: 30.4 },
  { symbol: "HPQ", name: "HP Inc.", sector: "Technology Hardware, Storage & Peripherals", roe: NaN },
  { symbol: "HUBB", name: "Hubbell Incorporated", sector: "Industrial Machinery & Supplies & Components", roe: 24.5 },
  { symbol: "HUM", name: "Humana", sector: "Managed Health Care", roe: 7 },
  { symbol: "HBAN", name: "Huntington Bancshares", sector: "Regional Banks", roe: 10.1 },
  { symbol: "HII", name: "Huntington Ingalls Industries", sector: "Aerospace & Defense", roe: 12.4 },
  { symbol: "IBM", name: "IBM", sector: "IT Consulting & Other Services", roe: 35.2 },
  { symbol: "IEX", name: "IDEX Corporation", sector: "Industrial Machinery & Supplies & Components", roe: 12.3 },
  { symbol: "IDXX", name: "Idexx Laboratories", sector: "Health Care Equipment", roe: 66.2 },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrial Machinery & Supplies & Components", roe: 93.7 },
  { symbol: "INCY", name: "Incyte", sector: "Biotechnology", roe: 29.9 },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrial Machinery & Supplies & Components", roe: 5.8 },
  { symbol: "PODD", name: "Insulet Corporation", sector: "Health Care Equipment", roe: 18.1 },
  { symbol: "INTC", name: "Intel", sector: "Semiconductors", roe: 0 },
  { symbol: "IBKR", name: "Interactive Brokers", sector: "Investment Banking & Brokerage", roe: 23.5 },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financial Exchanges & Data", roe: 11.9 },
  { symbol: "IFF", name: "International Flavors & Fragrances", sector: "Specialty Chemicals", roe: -2.6 },
  { symbol: "IP", name: "International Paper", sector: "Paper & Plastic Packaging Products & Materials", roe: -24.7 },
  { symbol: "INTU", name: "Intuit", sector: "Application Software", roe: 22 },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health Care Equipment", roe: 16.7 },
  { symbol: "IVZ", name: "Invesco", sector: "Asset Management & Custody Banks", roe: -1.2 },
  { symbol: "INVH", name: "Invitation Homes", sector: "Single-Family Residential REITs", roe: 6.1 },
  { symbol: "IQV", name: "IQVIA", sector: "Life Sciences Tools & Services", roe: 21.4 },
  { symbol: "IRM", name: "Iron Mountain", sector: "Other Specialized REITs", roe: NaN },
  { symbol: "JBHT", name: "J.B. Hunt", sector: "Cargo Ground Transportation", roe: 15.8 },
  { symbol: "JBL", name: "Jabil", sector: "Electronic Manufacturing Services", roe: 47.8 },
  { symbol: "JKHY", name: "Jack Henry & Associates", sector: "Transaction & Payment Processing Services", roe: 24.3 },
  { symbol: "J", name: "Jacobs Solutions", sector: "Construction & Engineering", roe: 9.7 },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Pharmaceuticals", roe: 35 },
  { symbol: "JCI", name: "Johnson Controls", sector: "Building Products", roe: 12.6 },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Diversified Banks", roe: 16.1 },
  { symbol: "KVUE", name: "Kenvue", sector: "Personal Care Products", roe: 14.4 },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Soft Drinks & Non-alcoholic Beverages", roe: 6.3 },
  { symbol: "KEY", name: "KeyCorp", sector: "Regional Banks", roe: 9.5 },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Electronic Equipment & Instruments", roe: 15.8 },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Household Products", roe: 126.6 },
  { symbol: "KIM", name: "Kimco Realty", sector: "Retail REITs", roe: 5.5 },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Oil & Gas Storage & Transportation", roe: 9.8 },
  { symbol: "KKR", name: "KKR & Co.", sector: "Asset Management & Custody Banks", roe: 8.9 },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Semiconductor Materials & Equipment", roe: 100.7 },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Packaged Foods & Meats", roe: -12.8 },
  { symbol: "KR", name: "Kroger", sector: "Food Retail", roe: 8 },
  { symbol: "LHX", name: "L3Harris", sector: "Aerospace & Defense", roe: 8.2 },
  { symbol: "LH", name: "Labcorp", sector: "Health Care Services", roe: 10.5 },
  { symbol: "LRCX", name: "Lam Research", sector: "Semiconductor Materials & Equipment", roe: 65.6 },
  { symbol: "LW", name: "Lamb Weston", sector: "Packaged Foods & Meats", roe: 23.2 },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Casinos & Gaming", roe: 73.3 },
  { symbol: "LDOS", name: "Leidos", sector: "Diversified Support Services", roe: 31 },
  { symbol: "LEN", name: "Lennar", sector: "Homebuilding", roe: 8.4 },
  { symbol: "LII", name: "Lennox International", sector: "Building Products", roe: 75.8 },
  { symbol: "LLY", name: "Lilly (Eli)", sector: "Pharmaceuticals", roe: 101.2 },
  { symbol: "LIN", name: "Linde plc", sector: "Industrial Gases", roe: 17.8 },
  { symbol: "LYV", name: "Live Nation Entertainment", sector: "Movies & Entertainment", roe: 36.7 },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Aerospace & Defense", roe: 76.9 },
  { symbol: "L", name: "Loews Corporation", sector: "Multi-line Insurance", roe: 9.4 },
  { symbol: "LOW", name: "Lowe's", sector: "Home Improvement Retail", roe: NaN },
  { symbol: "LULU", name: "Lululemon Athletica", sector: "Apparel, Accessories & Luxury Goods", roe: 41 },
  { symbol: "LYB", name: "LyondellBasell", sector: "Specialty Chemicals", roe: -6.9 },
  { symbol: "MTB", name: "M&T Bank", sector: "Regional Banks", roe: 9.8 },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Oil & Gas Refining & Marketing", roe: 24.3 },
  { symbol: "MAR", name: "Marriott International", sector: "Hotels, Resorts & Cruise Lines", roe: NaN },
  { symbol: "MRSH", name: "Marsh McLennan", sector: "Insurance Brokers", roe: 29.4 },
  { symbol: "MLM", name: "Martin Marietta Materials", sector: "Construction Materials", roe: 10.2 },
  { symbol: "MAS", name: "Masco", sector: "Building Products", roe: 7150 },
  { symbol: "MA", name: "Mastercard", sector: "Transaction & Payment Processing Services", roe: 209.9 },
  { symbol: "MTCH", name: "Match Group", sector: "Interactive Media & Services", roe: NaN },
  { symbol: "MKC", name: "McCormick & Company", sector: "Packaged Foods & Meats", roe: 14.2 },
  { symbol: "MCD", name: "McDonald's", sector: "Restaurants", roe: NaN },
  { symbol: "MCK", name: "McKesson Corporation", sector: "Health Care Distributors", roe: NaN },
  { symbol: "MDT", name: "Medtronic", sector: "Health Care Equipment", roe: NaN },
  { symbol: "MRK", name: "Merck & Co.", sector: "Pharmaceuticals", roe: 37.2 },
  { symbol: "META", name: "Meta Platforms", sector: "Interactive Media & Services", roe: 30.2 },
  { symbol: "MET", name: "MetLife", sector: "Life & Health Insurance", roe: 12 },
  { symbol: "MTD", name: "Mettler Toledo", sector: "Life Sciences Tools & Services", roe: NaN },
  { symbol: "MGM", name: "MGM Resorts", sector: "Casinos & Gaming", roe: 14.9 },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Semiconductors", roe: -1.1 },
  { symbol: "MU", name: "Micron Technology", sector: "Semiconductors", roe: 22.6 },
  { symbol: "MSFT", name: "Microsoft", sector: "Systems Software", roe: 34.4 },
  { symbol: "MAA", name: "Mid-America Apartment Communities", sector: "Multi-Family Residential REITs", roe: 7.6 },
  { symbol: "MRNA", name: "Moderna", sector: "Biotechnology", roe: -28.9 },
  { symbol: "MOH", name: "Molina Healthcare", sector: "Managed Health Care", roe: 11 },
  { symbol: "TAP", name: "Molson Coors Beverage Company", sector: "Brewers", roe: -18.2 },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Packaged Foods & Meats", roe: 9.3 },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Semiconductors", roe: 17.9 },
  { symbol: "MNST", name: "Monster Beverage", sector: "Soft Drinks & Non-alcoholic Beverages", roe: 25.5 },
  { symbol: "MCO", name: "Moody's Corporation", sector: "Financial Exchanges & Data", roe: 62.1 },
  { symbol: "MS", name: "Morgan Stanley", sector: "Investment Banking & Brokerage", roe: 15.6 },
  { symbol: "MOS", name: "Mosaic Company (The)", sector: "Fertilizers & Agricultural Chemicals", roe: 10.1 },
  { symbol: "MSI", name: "Motorola Solutions", sector: "Communications Equipment", roe: 104.2 },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Financial Exchanges & Data", roe: NaN },
  { symbol: "NDAQ", name: "Nasdaq, Inc.", sector: "Financial Exchanges & Data", roe: 15.3 },
  { symbol: "NTAP", name: "NetApp", sector: "Technology Hardware, Storage & Peripherals", roe: 125.3 },
  { symbol: "NFLX", name: "Netflix", sector: "Movies & Entertainment", roe: 42.8 },
  { symbol: "NEM", name: "Newmont", sector: "Gold", roe: 22.3 },
  { symbol: "NWSA", name: "News Corp (Class A)", sector: "Publishing", roe: 6.3 },
  { symbol: "NWS", name: "News Corp (Class B)", sector: "Publishing", roe: 6.3 },
  { symbol: "NEE", name: "NextEra Energy", sector: "Multi-Utilities", roe: 8.4 },
  { symbol: "NKE", name: "Nike, Inc.", sector: "Apparel, Accessories & Luxury Goods", roe: 18 },
  { symbol: "NI", name: "NiSource", sector: "Multi-Utilities", roe: 9.1 },
  { symbol: "NDSN", name: "Nordson Corporation", sector: "Industrial Machinery & Supplies & Components", roe: 17.5 },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Rail Transportation", roe: 19.2 },
  { symbol: "NTRS", name: "Northern Trust", sector: "Asset Management & Custody Banks", roe: 13.5 },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Aerospace & Defense", roe: 26.2 },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings", sector: "Hotels, Resorts & Cruise Lines", roe: 39.9 },
  { symbol: "NRG", name: "NRG Energy", sector: "Independent Power Producers & Energy Traders", roe: 64.2 },
  { symbol: "NUE", name: "Nucor", sector: "Steel", roe: 9.4 },
  { symbol: "NVDA", name: "Nvidia", sector: "Semiconductors", roe: 107.4 },
  { symbol: "NVR", name: "NVR, Inc.", sector: "Homebuilding", roe: 33.2 },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Semiconductors", roe: 20.7 },
  { symbol: "ORLY", name: "O’Reilly Automotive", sector: "Automotive Retail", roe: NaN },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Oil & Gas Exploration & Production", roe: 5.9 },
  { symbol: "ODFL", name: "Old Dominion", sector: "Cargo Ground Transportation", roe: 23.9 },
  { symbol: "OMC", name: "Omnicom Group", sector: "Advertising", roe: 0.5 },
  { symbol: "ON", name: "ON Semiconductor", sector: "Semiconductors", roe: 1.5 },
  { symbol: "OKE", name: "Oneok", sector: "Oil & Gas Storage & Transportation", roe: 17.8 },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Application Software", roe: 69 },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrial Machinery & Supplies & Components", roe: NaN },
  { symbol: "PCAR", name: "Paccar", sector: "Construction Machinery & Heavy Transportation Equipment", roe: 12.9 },
  { symbol: "PKG", name: "Packaging Corporation of America", sector: "Paper & Plastic Packaging Products & Materials", roe: 16.9 },
  { symbol: "PLTR", name: "Palantir Technologies", sector: "Application Software", roe: 26 },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Systems Software", roe: 16.3 },
  { symbol: "PSKY", name: "Paramount Skydance Corporation", sector: "Movies & Entertainment", roe: 1.3 },
  { symbol: "PH", name: "Parker Hannifin", sector: "Industrial Machinery & Supplies & Components", roe: 25.8 },
  { symbol: "PAYX", name: "Paychex", sector: "Human Resource & Employment Services", roe: 40.9 },
  { symbol: "PAYC", name: "Paycom", sector: "Human Resource & Employment Services", roe: 27.4 },
  { symbol: "PYPL", name: "PayPal", sector: "Transaction & Payment Processing Services", roe: 25.7 },
  { symbol: "PNR", name: "Pentair", sector: "Industrial Machinery & Supplies & Components", roe: 17.5 },
  { symbol: "PEP", name: "PepsiCo", sector: "Soft Drinks & Non-alcoholic Beverages", roe: 42.8 },
  { symbol: "PFE", name: "Pfizer", sector: "Pharmaceuticals", roe: 8.6 },
  { symbol: "PCG", name: "PG&E Corporation", sector: "Multi-Utilities", roe: 8.2 },
  { symbol: "PM", name: "Philip Morris International", sector: "Tobacco", roe: NaN },
  { symbol: "PSX", name: "Phillips 66", sector: "Oil & Gas Refining & Marketing", roe: 15.4 },
  { symbol: "PNW", name: "Pinnacle West Capital", sector: "Multi-Utilities", roe: 8.8 },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Diversified Banks", roe: 12.2 },
  { symbol: "POOL", name: "Pool Corporation", sector: "Distributors", roe: 33.1 },
  { symbol: "PPG", name: "PPG Industries", sector: "Specialty Chemicals", roe: 21.1 },
  { symbol: "PPL", name: "PPL Corporation", sector: "Electric Utilities", roe: 8.2 },
  { symbol: "PFG", name: "Principal Financial Group", sector: "Life & Health Insurance", roe: 10.5 },
  { symbol: "PG", name: "Procter & Gamble", sector: "Personal Care Products", roe: 31.6 },
  { symbol: "PGR", name: "Progressive Corporation", sector: "Property & Casualty Insurance", roe: 40.4 },
  { symbol: "PLD", name: "Prologis", sector: "Industrial REITs", roe: 6.1 },
  { symbol: "PRU", name: "Prudential Financial", sector: "Life & Health Insurance", roe: 11.4 },
  { symbol: "PEG", name: "Public Service Enterprise Group", sector: "Electric Utilities", roe: 12.6 },
  { symbol: "PTC", name: "PTC Inc.", sector: "Application Software", roe: 23.1 },
  { symbol: "PSA", name: "Public Storage", sector: "Self-Storage REITs", roe: 18.8 },
  { symbol: "PHM", name: "PulteGroup", sector: "Homebuilding", roe: 17.7 },
  { symbol: "PWR", name: "Quanta Services", sector: "Construction & Engineering", roe: 12.7 },
  { symbol: "QCOM", name: "Qualcomm", sector: "Semiconductors", roe: 21.5 },
  { symbol: "DGX", name: "Quest Diagnostics", sector: "Health Care Services", roe: 14.8 },
  { symbol: "Q", name: "Qnity Electronics", sector: "Semiconductor Materials & Equipment", roe: NaN },
  { symbol: "RL", name: "Ralph Lauren Corporation", sector: "Apparel, Accessories & Luxury Goods", roe: 33.8 },
  { symbol: "RJF", name: "Raymond James Financial", sector: "Investment Banking & Brokerage", roe: 17.1 },
  { symbol: "RTX", name: "RTX Corporation", sector: "Aerospace & Defense", roe: 11 },
  { symbol: "O", name: "Realty Income", sector: "Retail REITs", roe: 2.5 },
  { symbol: "REG", name: "Regency Centers", sector: "Retail REITs", roe: 7.7 },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Biotechnology", roe: 14.9 },
  { symbol: "RF", name: "Regions Financial Corporation", sector: "Regional Banks", roe: 11.7 },
  { symbol: "RSG", name: "Republic Services", sector: "Environmental & Facilities Services", roe: 18.3 },
  { symbol: "RMD", name: "ResMed", sector: "Health Care Equipment", roe: 25.7 },
  { symbol: "RVTY", name: "Revvity", sector: "Health Care Equipment", roe: 3.2 },
  { symbol: "HOOD", name: "Robinhood Markets", sector: "Investment Banking & Brokerage", roe: 22 },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Electrical Components & Equipment", roe: 23.7 },
  { symbol: "ROL", name: "Rollins, Inc.", sector: "Environmental & Facilities Services", roe: 38.9 },
  { symbol: "ROP", name: "Roper Technologies", sector: "Electronic Equipment & Instruments", roe: 7.9 },
  { symbol: "ROST", name: "Ross Stores", sector: "Apparel Retail", roe: 37.4 },
  { symbol: "RCL", name: "Royal Caribbean Group", sector: "Hotels, Resorts & Cruise Lines", roe: 47.7 },
  { symbol: "SPGI", name: "S&P Global", sector: "Financial Exchanges & Data", roe: 13.1 },
  { symbol: "CRM", name: "Salesforce", sector: "Application Software", roe: 12.2 },
  { symbol: "SNDK", name: "Sandisk", sector: "Technology Hardware, Storage & Peripherals", roe: -9.4 },
  { symbol: "SBAC", name: "SBA Communications", sector: "Telecom Tower REITs", roe: NaN },
  { symbol: "SLB", name: "Schlumberger", sector: "Oil & Gas Equipment & Services", roe: 13.9 },
  { symbol: "STX", name: "Seagate Technology", sector: "Technology Hardware, Storage & Peripherals", roe: NaN },
  { symbol: "SRE", name: "Sempra", sector: "Multi-Utilities", roe: 6.8 },
  { symbol: "NOW", name: "ServiceNow", sector: "Systems Software", roe: 15.5 },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Specialty Chemicals", roe: 59.4 },
  { symbol: "SPG", name: "Simon Property Group", sector: "Retail REITs", roe: 104.1 },
  { symbol: "SWKS", name: "Skyworks Solutions", sector: "Semiconductors", roe: 6.5 },
  { symbol: "SJM", name: "J.M. Smucker Company (The)", sector: "Packaged Foods & Meats", roe: -17.4 },
  { symbol: "SW", name: "Smurfit Westrock", sector: "Paper & Plastic Packaging Products & Materials", roe: 3.9 },
  { symbol: "SNA", name: "Snap-on", sector: "Industrial Machinery & Supplies & Components", roe: 18.3 },
  { symbol: "SOLV", name: "Solventum", sector: "Health Care Technology", roe: 37.3 },
  { symbol: "SO", name: "Southern Company", sector: "Electric Utilities", roe: 11 },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Passenger Airlines", roe: 4.8 },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrial Machinery & Supplies & Components", roe: 4.5 },
  { symbol: "SBUX", name: "Starbucks", sector: "Restaurants", roe: NaN },
  { symbol: "STT", name: "State Street Corporation", sector: "Asset Management & Custody Banks", roe: 11.1 },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Steel", roe: 13.3 },
  { symbol: "STE", name: "Steris", sector: "Health Care Equipment", roe: 10.5 },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Health Care Equipment", roe: 15.1 },
  { symbol: "SMCI", name: "Supermicro", sector: "Technology Hardware, Storage & Peripherals", roe: 13.2 },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Consumer Finance", roe: 21.3 },
  { symbol: "SNPS", name: "Synopsys", sector: "Application Software", roe: 7.2 },
  { symbol: "SYY", name: "Sysco", sector: "Food Distributors", roe: 82.3 },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Wireless Telecommunication Services", roe: 18.2 },
  { symbol: "TROW", name: "T. Rowe Price", sector: "Asset Management & Custody Banks", roe: 18.8 },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Interactive Home Entertainment", roe: -86.2 },
  { symbol: "TPR", name: "Tapestry, Inc.", sector: "Apparel, Accessories & Luxury Goods", roe: 55.3 },
  { symbol: "TRGP", name: "Targa Resources", sector: "Oil & Gas Storage & Transportation", roe: 51.4 },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Staples Merchandise Retail", roe: 25.1 },
  { symbol: "TEL", name: "TE Connectivity", sector: "Electronic Manufacturing Services", roe: 16.1 },
  { symbol: "TDY", name: "Teledyne Technologies", sector: "Electronic Equipment & Instruments", roe: 8.9 },
  { symbol: "TER", name: "Teradyne", sector: "Semiconductor Materials & Equipment", roe: 19.7 },
  { symbol: "TSLA", name: "Tesla, Inc.", sector: "Automobile Manufacturers", roe: 4.9 },
  { symbol: "TXN", name: "Texas Instruments", sector: "Semiconductors", roe: 30.1 },
  { symbol: "TPL", name: "Texas Pacific Land Corporation", sector: "Oil & Gas Exploration & Production", roe: 37.2 },
  { symbol: "TXT", name: "Textron", sector: "Aerospace & Defense", roe: 12.2 },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Life Sciences Tools & Services", roe: 13 },
  { symbol: "TJX", name: "TJX Companies", sector: "Apparel Retail", roe: 58.4 },
  { symbol: "TKO", name: "TKO Group Holdings", sector: "Movies & Entertainment", roe: 8.1 },
  { symbol: "TTD", name: "Trade Desk (The)", sector: "Advertising", roe: 16.8 },
  { symbol: "TSCO", name: "Tractor Supply", sector: "Other Specialty Retail", roe: 45.2 },
  { symbol: "TT", name: "Trane Technologies", sector: "Building Products", roe: 37 },
  { symbol: "TDG", name: "TransDigm Group", sector: "Aerospace & Defense", roe: NaN },
  { symbol: "TRV", name: "Travelers Companies (The)", sector: "Property & Casualty Insurance", roe: 20.7 },
  { symbol: "TRMB", name: "Trimble Inc.", sector: "Electronic Equipment & Instruments", roe: 7.3 },
  { symbol: "TFC", name: "Truist Financial", sector: "Diversified Banks", roe: 8.2 },
  { symbol: "TYL", name: "Tyler Technologies", sector: "Application Software", roe: 8.9 },
  { symbol: "TSN", name: "Tyson Foods", sector: "Packaged Foods & Meats", roe: 1.3 },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Diversified Banks", roe: 12.2 },
  { symbol: "UBER", name: "Uber", sector: "Passenger Ground Transportation", roe: 39.9 },
  { symbol: "UDR", name: "UDR, Inc.", sector: "Multi-Family Residential REITs", roe: 9.4 },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Other Specialty Retail", roe: 48 },
  { symbol: "UNP", name: "Union Pacific Corporation", sector: "Rail Transportation", roe: 40.4 },
  { symbol: "UAL", name: "United Airlines Holdings", sector: "Passenger Airlines", roe: 24 },
  { symbol: "UPS", name: "United Parcel Service", sector: "Air Freight & Logistics", roe: 33.8 },
  { symbol: "URI", name: "United Rentals", sector: "Trading Companies & Distributors", roe: 28.4 },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Managed Health Care", roe: 12.5 },
  { symbol: "UHS", name: "Universal Health Services", sector: "Health Care Facilities", roe: 20 },
  { symbol: "VLO", name: "Valero Energy", sector: "Oil & Gas Refining & Marketing", roe: 8.3 },
  { symbol: "VTR", name: "Ventas", sector: "Health Care REITs", roe: 2.2 },
  { symbol: "VLTO", name: "Veralto", sector: "Environmental & Facilities Services", roe: 36.5 },
  { symbol: "VRSN", name: "Verisign", sector: "Internet Services & Infrastructure", roe: NaN },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Research & Consulting Services", roe: 437.9 },
  { symbol: "VZ", name: "Verizon", sector: "Integrated Telecommunication Services", roe: 17.1 },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Biotechnology", roe: 22.5 },
  { symbol: "VTRS", name: "Viatris", sector: "Pharmaceuticals", roe: -21.1 },
  { symbol: "VICI", name: "Vici Properties", sector: "Hotel & Resort REITs", roe: 10.4 },
  { symbol: "V", name: "Visa Inc.", sector: "Transaction & Payment Processing Services", roe: 54 },
  { symbol: "VST", name: "Vistra Corp.", sector: "Electric Utilities", roe: 17.3 },
  { symbol: "VMC", name: "Vulcan Materials Company", sector: "Construction Materials", roe: 13 },
  { symbol: "WRB", name: "W. R. Berkley Corporation", sector: "Property & Casualty Insurance", roe: 19.6 },
  { symbol: "GWW", name: "W. W. Grainger", sector: "Industrial Machinery & Supplies & Components", roe: 46.1 },
  { symbol: "WAB", name: "Wabtec", sector: "Construction Machinery & Heavy Transportation Equipment", roe: 11.1 },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples Merchandise Retail", roe: 21.8 },
  { symbol: "DIS", name: "Walt Disney Company (The)", sector: "Movies & Entertainment", roe: 12 },
  { symbol: "WBD", name: "Warner Bros. Discovery", sector: "Broadcasting", roe: 1 },
  { symbol: "WM", name: "Waste Management", sector: "Environmental & Facilities Services", roe: 29.7 },
  { symbol: "WAT", name: "Waters Corporation", sector: "Life Sciences Tools & Services", roe: 29.3 },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Electric Utilities", roe: 11.6 },
  { symbol: "WFC", name: "Wells Fargo", sector: "Diversified Banks", roe: 11.7 },
  { symbol: "WELL", name: "Welltower", sector: "Health Care REITs", roe: 2.5 },
  { symbol: "WST", name: "West Pharmaceutical Services", sector: "Health Care Supplies", roe: 16.9 },
  { symbol: "WDC", name: "Western Digital", sector: "Technology Hardware, Storage & Peripherals", roe: 41.1 },
  { symbol: "WY", name: "Weyerhaeuser", sector: "Timber REITs", roe: 3.4 },
  { symbol: "WSM", name: "Williams-Sonoma, Inc.", sector: "Homefurnishing Retail", roe: 56.9 },
  { symbol: "WMB", name: "Williams Companies", sector: "Oil & Gas Storage & Transportation", roe: 18.6 },
  { symbol: "WTW", name: "Willis Towers Watson", sector: "Insurance Brokers", roe: 20.1 },
  { symbol: "WDAY", name: "Workday, Inc.", sector: "Application Software", roe: 7.3 },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Casinos & Gaming", roe: NaN },
  { symbol: "XEL", name: "Xcel Energy", sector: "Multi-Utilities", roe: 9.9 },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrial Machinery & Supplies & Components", roe: 8.4 },
  { symbol: "YUM", name: "Yum! Brands", sector: "Restaurants", roe: NaN },
  { symbol: "ZBRA", name: "Zebra Technologies", sector: "Electronic Equipment & Instruments", roe: 11.7 },
  { symbol: "ZBH", name: "Zimmer Biomet", sector: "Health Care Equipment", roe: 5.6 },
  { symbol: "ZTS", name: "Zoetis", sector: "Pharmaceuticals", roe: 66 },
];
